name: CI staging

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just_a_placeholder_to_avoid_errors'
      - name: Adding know hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Build project
        run: NODE_ENV=production yarn build
      - name: Rsync project with server one
        run: rsync -r --exclude="config/database.js" --exclude="config/server.js" . ${{ secrets.SERVER }}:${{ secrets.STAGING_FOLDER }}
      - name: Restart server
        run: ssh ${{ secrets.SERVER }} pm2 reload ${{ secrets.STAGING_PROCESS_NAME }}
